### ISSUE TITLE
One more case study - Sahaj Software

### ISSUE THREAD

**Issue by PrithviRajNarendra** [sizovs/open-salaries#3]
First of all, thank you for compiling this resource. 🙏 

Here is one more company, Sahaj Software, with an open salary policy. Here are some articles explaining their thought process and methodology. 
https://sahaj.ai/stories/open-salaries
https://sahaj.ai/stories/open-hikes-and-compensation

**Comment by priyaaank** [comment]
I am one of the members at Sahaj and here is a coverage by BBC a while back. (https://www.bbc.co.uk/programmes/p0cl3ws5) 

Happy to provide more info if it helps add it to the list.

**Comment by sizovs** [comment]
Added https://github.com/sizovs/open-salaries/pull/4
